baseURL = "https://jbelborja.github.io/profile/"
languageCode = "en"
title = "Javier Bel"
theme = "PaperMod"
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience/"
    weight = 20

[params.profileMode]
  enabled = true
  title = "Javier Bel"
  subtitle = "Senior Software Engineer"
  imageUrl = "/profile/images/avatar.png"
  imageWidth = 120
  imageHeight = 120
  imageDisplayKind = "circle"

[[params.socialIcons]]
  name = "email"
  url = "mailto:jbelborja@gmail.com"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/jbelborja"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/jbelborja"


